// Generated by Selenium IDE


import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchAndAddTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchAndAdd() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(786, 824));
    driver.findElement(By.cssSelector("div:nth-child(2) > div > form > label > input")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > div > form > label > input")).sendKeys("egg");
    driver.findElement(By.cssSelector("div:nth-child(2) > div > form > input")).click();
    assertThat(driver.switchTo().alert().getText(), is("A search for egg was submitted"));
    driver.findElement(By.cssSelector("div:nth-child(1) > div > form input:nth-child(1)")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > div > form input:nth-child(1)")).sendKeys("Time to say Bruh?");
    driver.findElement(By.cssSelector("label > input:nth-child(2)")).click();
    driver.findElement(By.cssSelector("label > input:nth-child(2)")).sendKeys("1");
    driver.findElement(By.cssSelector("input:nth-child(3)")).click();
    driver.findElement(By.cssSelector("input:nth-child(3)")).sendKeys("Here be descriptions");
    driver.findElement(By.cssSelector("input:nth-child(4)")).click();
    driver.findElement(By.cssSelector("input:nth-child(4)")).sendKeys("5");
    driver.findElement(By.cssSelector("div:nth-child(1) > div > form > input")).click();
    assertThat(driver.switchTo().alert().getText(), is("A name was submitted: Time to say Bruh?"));
    driver.findElement(By.cssSelector("div:nth-child(2) > div > form > label > input")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > div > form > label > input")).sendKeys("Time");
    driver.findElement(By.cssSelector("div:nth-child(2) > div > form > input")).click();
    assertThat(driver.switchTo().alert().getText(), is("A search for Time was submitted"));
  }
}
